######################## default configuration ####################
baseURL = "https://hsuan.app/"
title = "Hsuan網路"
theme = "bigspring-light"
# post pagination
paginate = "3"
# post excerpt
summaryLength = "15"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# google analytics
googleAnalytics = "G-NMCWKV75ET" # example : UA-123-45
# unsafe html
[markup.goldmark.renderer]
unsafe = true