# main menu
[[main]]
name = "主頁"
url = "/"
weight = 1

[[main]]
name = "部落格"
url = "https://blog.hsuan.app"
weight = 2

[[main]]
name = "價格"
url = "pricing"
weight = 3

[[main]]
name = "聯絡"
url = "contact"
weight = 4

[[main]]
name = "常見問題"
url = "faq"
weight = 5

# footer menu left
[[footer_left]]
name = "關於我們"
url = "#"

# footer menu middle
[[footer_middle]]
name = "產品總覽"
url = "products"

[[footer_middle]]
name = "價格"
url = "pricing"

[[footer_middle]]
name = "特點"
url = "#"

# footer menu right
[[footer_right]]
name = "隱私權政策"
url = "https://policy.hsuan.app/privacy"

[[footer_right]]
name = "授權條款"
url = "https://policy.hsuan.app/copyright"

[[footer_right]]
name = "服務條款"
url = "https://policy.hsuan.app/terms"

[[footer_right]]
name = "FAQ"
url = "faq"